language: "perl"
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"

install:
  - "cpanm -n Test::More Test::Deep Test::Exception Test::Warn"
  - "cpanm -n DBD::SQLite"
  - "cpanm -n --installdeps ."
